name: GriefBoard
version: 1.0
main: ru.griefboard.GriefBoard
api-version: 1.16
description: Sidebar scoreboard in GhostGrief style

commands:
  griefboard:
    description: Управление скорбордом
    aliases: [gsb]
    permission: griefboard.admin
  login:
    description: Вход в аккаунт
    aliases: [l, log]
  register:
    description: Регистрация
    aliases: [reg]
  changepassword:
    description: Смена пароля
    aliases: [changepass]
  clan:
    description: Кланы
    aliases: [clans]
  cc:
    description: Чат клана
    aliases: [clanchat]
  tpa:
    description: Запрос на телепорт к игроку
  tpahere:
    description: Попросить игрока телепортироваться к тебе
    aliases: [tpah]
  tpaccept:
    description: Принять запрос телепорта
    aliases: [tpyes]
  tpdeny:
    description: Отклонить запрос телепорта
    aliases: [tpno]
  tpcancel:
    description: Отменить свои запросы телепорта
  tptoggle:
    description: Включить или выключить запросы телепорта
  spawn:
    description: Телепорт на спавн
    aliases: [lobby, hub]
  rank:
    description: Выдача рангов
    permission: griefboard.admin
  rtp:
    description: Случайная телепортация в основной мир
    permission: griefboard.rtp

permissions:
  griefboard.rtp:
    default: true
  griefboard.admin:
    default: op
